function [bow_features, labels] = get_bows_with_labels(cell_of_structs, clustering_model, density, colorspace_idx)
%GET_BOW_WITH_LABELS Prepares Bag-of-words features and targets for each
%image
%
%   [BOW_FEATURES, LABELS] = GET_BOWS_WITH_LABELS(CELL_OF_STRUCTS,
%   CLUSTERING_MODEL) returns a matrix with BOW features and targets
%   corresponding to each image in CELL_OF_STRUCTS
%
% Inputs:
%   CELL_OF_STRUCTS: cell of image structs generated from
%   data_preprocessing
%   CLUSTERING_MODEL: a trained clustering model generated by
%   execute_clustering
%   DENSITY: sampling type density, one of 'dense' or 'key'
%   COLORSPACE_IDX: Index of the colorspace 
%
% Outputs:
%   BOW_FEATURES: an NxP matrix, where N is the number of images and P is
%   the number of clusters. Each row is the BoW representation of the image
%   with respect to the clustering model centroids
%   TARGETS: a Nx1 vector with labels for each image (1-4)
%
%See Also
%execute_clustering
%data_preprocessing


    % Initialize matrices
    N = length(cell_of_structs);
    P = clustering_model.num_clusters;
    bow_features = zeros(N,P);
    labels = zeros(N,1);

    for i=1:N % for each image struct
       image = cell_of_structs{i}; 
       features = getfield(image, density);
       bow_features(i,:) = get_image_bow(features{colorspace_idx}, clustering_model); % get bow
       labels(i) = image.label; % save target (1-4)
    end
    
end