function [data] = load_data_from_folder (folder_path, num_samples)
%LOAD_DATA_FROM_FOLDER Loads image feature structs 
%
%   DATA = LOAD_DATA_FROM_FOLDER(FOLDER_PATH, NUM_SAMPLES) Returns all, or
%   a random subsample, or image feature structs (generated by data_preprocessing) from a specified
%   directory. 
%
% Inputs:
%   FOLDER_PATH: Relative or Absolute path containing image structs (for ex. data/training/clustering)
%   NUM_SAMPLES: Number of random subsamples to return. Set to 0 to obtain
%   all structs
%
% Outputs:
%   DATA: Cell of structs
%See Also:
%DATA_PREPROCESSING

    files = dir(folder_path); % all files in directory
    files = {files.name};
    files = {files{3:end}}; % exclude first two items '.' and '..'
    
    data = cell(1,length(files)); % where structs will be stored
    
    if nargin > 1 && num_samples > 0
        files =  randsample(files, num_samples); % sample randomly from files
    end
    
    % load data
    for f=1:length(files)
        fpath = char(strcat(folder_path, files{f}));
        tmp_struct = load( fpath, '-mat');
        data{f} = tmp_struct.image;
    end
end